### ISSUE TITLE
Latest commit won't compile

### ISSUE THREAD

**Issue by bontebok** [lorow/OpenIris#27]
Here's the output from the compiler -

```
lib/src/network/stream/streamServer.cpp:87:17: error: 'RTC_CNTL_BROWN_OUT_REG' was not declared in this scope
  WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0); //! Turn-off the 'brownout detector'
                 ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by lorow** [comment]
Found the issue, I didn't an updated version of the streamServer.hpp file, my bad! 

It should compile now, thank you for reporting it!

**Comment by bontebok** [comment]
Thank you!

**Comment by bontebok** [comment]
Confirming a successful compile. Closing issue. Thanks again
