### ISSUE TITLE
Two WifiHandler folders?

### ISSUE THREAD

**Issue by TheGuardianWolf** [lorow/OpenIris#50]
There are two WifiHandler folders here:

https://github.com/lorow/OpenIris/tree/master/ESP/lib/src/network

It's causing issues for windows clone, I think the one with CapsCase is not used?

**Comment by ZanzyTHEbar** [comment]
Thank you for pointing this out - this is absolutely a big with GitHub and merges. We will fix it promptly.

**Comment by ZanzyTHEbar** [comment]
Fixed. Thank you again.
