### ISSUE TITLE
Issue with default compile

### ISSUE THREAD

**Issue by TheGuardianWolf** [lorow/OpenIris#53]
Hey, I've been using this a while, and I've had to make this modification for the default (AIThinker) config to compile.

![image](https://github.com/lorow/OpenIris/assets/8168401/c297bc63-1d03-44f6-bb60-071a2ef2bc8a)

Is this just me or an actual isse?

**Comment by lorow** [comment]
Hi! 

It's a symptom of an outdated Platformio SDK, they deprecated the `sscb` fields a while ago in favour of `sccb`. 

To fix that in the newest version you can simply update the sdk like so: https://docs.eyetrackvr.dev/firmware_guide/update_platformio

**Comment by TheGuardianWolf** [comment]
Thanks! This is resolved, I'll mark as closed
